// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/loads"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/runtime/security"
	"github.com/go-openapi/spec"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/olelarssen/provider/restapi/operations/instruments"
	"github.com/olelarssen/provider/restapi/operations/public"
)

// NewProviderServiceAPI creates a new ProviderService instance
func NewProviderServiceAPI(spec *loads.Document) *ProviderServiceAPI {
	return &ProviderServiceAPI{
		handlers:            make(map[string]map[string]http.Handler),
		formats:             strfmt.Default,
		defaultConsumes:     "application/json",
		defaultProduces:     "application/json",
		customConsumers:     make(map[string]runtime.Consumer),
		customProducers:     make(map[string]runtime.Producer),
		PreServerShutdown:   func() {},
		ServerShutdown:      func() {},
		spec:                spec,
		useSwaggerUI:        false,
		ServeError:          errors.ServeError,
		BasicAuthenticator:  security.BasicAuth,
		APIKeyAuthenticator: security.APIKeyAuth,
		BearerAuthenticator: security.BearerAuth,

		JSONConsumer:    runtime.JSONConsumer(),
		UrlformConsumer: runtime.DiscardConsumer,

		JSONProducer: runtime.JSONProducer(),

		PublicGetAuthorizeHandler: public.GetAuthorizeHandlerFunc(func(params public.GetAuthorizeParams) middleware.Responder {
			return middleware.NotImplemented("operation public.GetAuthorize has not yet been implemented")
		}),
		PublicGetCredentialsHandler: public.GetCredentialsHandlerFunc(func(params public.GetCredentialsParams) middleware.Responder {
			return middleware.NotImplemented("operation public.GetCredentials has not yet been implemented")
		}),
		PublicGetGoogleCallbackHandler: public.GetGoogleCallbackHandlerFunc(func(params public.GetGoogleCallbackParams) middleware.Responder {
			return middleware.NotImplemented("operation public.GetGoogleCallback has not yet been implemented")
		}),
		PublicGetGoogleLoginHandler: public.GetGoogleLoginHandlerFunc(func(params public.GetGoogleLoginParams) middleware.Responder {
			return middleware.NotImplemented("operation public.GetGoogleLogin has not yet been implemented")
		}),
		InstrumentsGetMetricsHandler: instruments.GetMetricsHandlerFunc(func(params instruments.GetMetricsParams) middleware.Responder {
			return middleware.NotImplemented("operation instruments.GetMetrics has not yet been implemented")
		}),
		PublicGetPingHandler: public.GetPingHandlerFunc(func(params public.GetPingParams) middleware.Responder {
			return middleware.NotImplemented("operation public.GetPing has not yet been implemented")
		}),
		PublicGetValidateHandler: public.GetValidateHandlerFunc(func(params public.GetValidateParams) middleware.Responder {
			return middleware.NotImplemented("operation public.GetValidate has not yet been implemented")
		}),
		PublicGetYandexCallbackHandler: public.GetYandexCallbackHandlerFunc(func(params public.GetYandexCallbackParams) middleware.Responder {
			return middleware.NotImplemented("operation public.GetYandexCallback has not yet been implemented")
		}),
		PublicGetYandexLoginHandler: public.GetYandexLoginHandlerFunc(func(params public.GetYandexLoginParams) middleware.Responder {
			return middleware.NotImplemented("operation public.GetYandexLogin has not yet been implemented")
		}),
		PublicPostRefreshHandler: public.PostRefreshHandlerFunc(func(params public.PostRefreshParams) middleware.Responder {
			return middleware.NotImplemented("operation public.PostRefresh has not yet been implemented")
		}),
		PublicPostTokenHandler: public.PostTokenHandlerFunc(func(params public.PostTokenParams) middleware.Responder {
			return middleware.NotImplemented("operation public.PostToken has not yet been implemented")
		}),
	}
}

/*ProviderServiceAPI the provider service API */
type ProviderServiceAPI struct {
	spec            *loads.Document
	context         *middleware.Context
	handlers        map[string]map[string]http.Handler
	formats         strfmt.Registry
	customConsumers map[string]runtime.Consumer
	customProducers map[string]runtime.Producer
	defaultConsumes string
	defaultProduces string
	Middleware      func(middleware.Builder) http.Handler
	useSwaggerUI    bool

	// BasicAuthenticator generates a runtime.Authenticator from the supplied basic auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	BasicAuthenticator func(security.UserPassAuthentication) runtime.Authenticator

	// APIKeyAuthenticator generates a runtime.Authenticator from the supplied token auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	APIKeyAuthenticator func(string, string, security.TokenAuthentication) runtime.Authenticator

	// BearerAuthenticator generates a runtime.Authenticator from the supplied bearer token auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	BearerAuthenticator func(string, security.ScopedTokenAuthentication) runtime.Authenticator

	// JSONConsumer registers a consumer for the following mime types:
	//   - application/json
	JSONConsumer runtime.Consumer
	// UrlformConsumer registers a consumer for the following mime types:
	//   - application/x-www-form-urlencoded
	UrlformConsumer runtime.Consumer

	// JSONProducer registers a producer for the following mime types:
	//   - application/json
	JSONProducer runtime.Producer

	// PublicGetAuthorizeHandler sets the operation handler for the get authorize operation
	PublicGetAuthorizeHandler public.GetAuthorizeHandler
	// PublicGetCredentialsHandler sets the operation handler for the get credentials operation
	PublicGetCredentialsHandler public.GetCredentialsHandler
	// PublicGetGoogleCallbackHandler sets the operation handler for the get google callback operation
	PublicGetGoogleCallbackHandler public.GetGoogleCallbackHandler
	// PublicGetGoogleLoginHandler sets the operation handler for the get google login operation
	PublicGetGoogleLoginHandler public.GetGoogleLoginHandler
	// InstrumentsGetMetricsHandler sets the operation handler for the get metrics operation
	InstrumentsGetMetricsHandler instruments.GetMetricsHandler
	// PublicGetPingHandler sets the operation handler for the get ping operation
	PublicGetPingHandler public.GetPingHandler
	// PublicGetValidateHandler sets the operation handler for the get validate operation
	PublicGetValidateHandler public.GetValidateHandler
	// PublicGetYandexCallbackHandler sets the operation handler for the get yandex callback operation
	PublicGetYandexCallbackHandler public.GetYandexCallbackHandler
	// PublicGetYandexLoginHandler sets the operation handler for the get yandex login operation
	PublicGetYandexLoginHandler public.GetYandexLoginHandler
	// PublicPostRefreshHandler sets the operation handler for the post refresh operation
	PublicPostRefreshHandler public.PostRefreshHandler
	// PublicPostTokenHandler sets the operation handler for the post token operation
	PublicPostTokenHandler public.PostTokenHandler

	// ServeError is called when an error is received, there is a default handler
	// but you can set your own with this
	ServeError func(http.ResponseWriter, *http.Request, error)

	// PreServerShutdown is called before the HTTP(S) server is shutdown
	// This allows for custom functions to get executed before the HTTP(S) server stops accepting traffic
	PreServerShutdown func()

	// ServerShutdown is called when the HTTP(S) server is shut down and done
	// handling all active connections and does not accept connections any more
	ServerShutdown func()

	// Custom command line argument groups with their descriptions
	CommandLineOptionsGroups []swag.CommandLineOptionsGroup

	// User defined logger function.
	Logger func(string, ...interface{})
}

// UseRedoc for documentation at /docs
func (o *ProviderServiceAPI) UseRedoc() {
	o.useSwaggerUI = false
}

// UseSwaggerUI for documentation at /docs
func (o *ProviderServiceAPI) UseSwaggerUI() {
	o.useSwaggerUI = true
}

// SetDefaultProduces sets the default produces media type
func (o *ProviderServiceAPI) SetDefaultProduces(mediaType string) {
	o.defaultProduces = mediaType
}

// SetDefaultConsumes returns the default consumes media type
func (o *ProviderServiceAPI) SetDefaultConsumes(mediaType string) {
	o.defaultConsumes = mediaType
}

// SetSpec sets a spec that will be served for the clients.
func (o *ProviderServiceAPI) SetSpec(spec *loads.Document) {
	o.spec = spec
}

// DefaultProduces returns the default produces media type
func (o *ProviderServiceAPI) DefaultProduces() string {
	return o.defaultProduces
}

// DefaultConsumes returns the default consumes media type
func (o *ProviderServiceAPI) DefaultConsumes() string {
	return o.defaultConsumes
}

// Formats returns the registered string formats
func (o *ProviderServiceAPI) Formats() strfmt.Registry {
	return o.formats
}

// RegisterFormat registers a custom format validator
func (o *ProviderServiceAPI) RegisterFormat(name string, format strfmt.Format, validator strfmt.Validator) {
	o.formats.Add(name, format, validator)
}

// Validate validates the registrations in the ProviderServiceAPI
func (o *ProviderServiceAPI) Validate() error {
	var unregistered []string

	if o.JSONConsumer == nil {
		unregistered = append(unregistered, "JSONConsumer")
	}
	if o.UrlformConsumer == nil {
		unregistered = append(unregistered, "UrlformConsumer")
	}

	if o.JSONProducer == nil {
		unregistered = append(unregistered, "JSONProducer")
	}

	if o.PublicGetAuthorizeHandler == nil {
		unregistered = append(unregistered, "public.GetAuthorizeHandler")
	}
	if o.PublicGetCredentialsHandler == nil {
		unregistered = append(unregistered, "public.GetCredentialsHandler")
	}
	if o.PublicGetGoogleCallbackHandler == nil {
		unregistered = append(unregistered, "public.GetGoogleCallbackHandler")
	}
	if o.PublicGetGoogleLoginHandler == nil {
		unregistered = append(unregistered, "public.GetGoogleLoginHandler")
	}
	if o.InstrumentsGetMetricsHandler == nil {
		unregistered = append(unregistered, "instruments.GetMetricsHandler")
	}
	if o.PublicGetPingHandler == nil {
		unregistered = append(unregistered, "public.GetPingHandler")
	}
	if o.PublicGetValidateHandler == nil {
		unregistered = append(unregistered, "public.GetValidateHandler")
	}
	if o.PublicGetYandexCallbackHandler == nil {
		unregistered = append(unregistered, "public.GetYandexCallbackHandler")
	}
	if o.PublicGetYandexLoginHandler == nil {
		unregistered = append(unregistered, "public.GetYandexLoginHandler")
	}
	if o.PublicPostRefreshHandler == nil {
		unregistered = append(unregistered, "public.PostRefreshHandler")
	}
	if o.PublicPostTokenHandler == nil {
		unregistered = append(unregistered, "public.PostTokenHandler")
	}

	if len(unregistered) > 0 {
		return fmt.Errorf("missing registration: %s", strings.Join(unregistered, ", "))
	}

	return nil
}

// ServeErrorFor gets a error handler for a given operation id
func (o *ProviderServiceAPI) ServeErrorFor(operationID string) func(http.ResponseWriter, *http.Request, error) {
	return o.ServeError
}

// AuthenticatorsFor gets the authenticators for the specified security schemes
func (o *ProviderServiceAPI) AuthenticatorsFor(schemes map[string]spec.SecurityScheme) map[string]runtime.Authenticator {
	return nil
}

// Authorizer returns the registered authorizer
func (o *ProviderServiceAPI) Authorizer() runtime.Authorizer {
	return nil
}

// ConsumersFor gets the consumers for the specified media types.
// MIME type parameters are ignored here.
func (o *ProviderServiceAPI) ConsumersFor(mediaTypes []string) map[string]runtime.Consumer {
	result := make(map[string]runtime.Consumer, len(mediaTypes))
	for _, mt := range mediaTypes {
		switch mt {
		case "application/json":
			result["application/json"] = o.JSONConsumer
		case "application/x-www-form-urlencoded":
			result["application/x-www-form-urlencoded"] = o.UrlformConsumer
		}

		if c, ok := o.customConsumers[mt]; ok {
			result[mt] = c
		}
	}
	return result
}

// ProducersFor gets the producers for the specified media types.
// MIME type parameters are ignored here.
func (o *ProviderServiceAPI) ProducersFor(mediaTypes []string) map[string]runtime.Producer {
	result := make(map[string]runtime.Producer, len(mediaTypes))
	for _, mt := range mediaTypes {
		switch mt {
		case "application/json":
			result["application/json"] = o.JSONProducer
		}

		if p, ok := o.customProducers[mt]; ok {
			result[mt] = p
		}
	}
	return result
}

// HandlerFor gets a http.Handler for the provided operation method and path
func (o *ProviderServiceAPI) HandlerFor(method, path string) (http.Handler, bool) {
	if o.handlers == nil {
		return nil, false
	}
	um := strings.ToUpper(method)
	if _, ok := o.handlers[um]; !ok {
		return nil, false
	}
	if path == "/" {
		path = ""
	}
	h, ok := o.handlers[um][path]
	return h, ok
}

// Context returns the middleware context for the provider service API
func (o *ProviderServiceAPI) Context() *middleware.Context {
	if o.context == nil {
		o.context = middleware.NewRoutableContext(o.spec, o, nil)
	}

	return o.context
}

func (o *ProviderServiceAPI) initHandlerCache() {
	o.Context() // don't care about the result, just that the initialization happened
	if o.handlers == nil {
		o.handlers = make(map[string]map[string]http.Handler)
	}

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/authorize"] = public.NewGetAuthorize(o.context, o.PublicGetAuthorizeHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/credentials"] = public.NewGetCredentials(o.context, o.PublicGetCredentialsHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/google/callback"] = public.NewGetGoogleCallback(o.context, o.PublicGetGoogleCallbackHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/google/login"] = public.NewGetGoogleLogin(o.context, o.PublicGetGoogleLoginHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/metrics"] = instruments.NewGetMetrics(o.context, o.InstrumentsGetMetricsHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/ping"] = public.NewGetPing(o.context, o.PublicGetPingHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/validate"] = public.NewGetValidate(o.context, o.PublicGetValidateHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/yandex/callback"] = public.NewGetYandexCallback(o.context, o.PublicGetYandexCallbackHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/yandex/login"] = public.NewGetYandexLogin(o.context, o.PublicGetYandexLoginHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/refresh"] = public.NewPostRefresh(o.context, o.PublicPostRefreshHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/token"] = public.NewPostToken(o.context, o.PublicPostTokenHandler)
}

// Serve creates a http handler to serve the API over HTTP
// can be used directly in http.ListenAndServe(":8000", api.Serve(nil))
func (o *ProviderServiceAPI) Serve(builder middleware.Builder) http.Handler {
	o.Init()

	if o.Middleware != nil {
		return o.Middleware(builder)
	}
	if o.useSwaggerUI {
		return o.context.APIHandlerSwaggerUI(builder)
	}
	return o.context.APIHandler(builder)
}

// Init allows you to just initialize the handler cache, you can then recompose the middleware as you see fit
func (o *ProviderServiceAPI) Init() {
	if len(o.handlers) == 0 {
		o.initHandlerCache()
	}
}

// RegisterConsumer allows you to add (or override) a consumer for a media type.
func (o *ProviderServiceAPI) RegisterConsumer(mediaType string, consumer runtime.Consumer) {
	o.customConsumers[mediaType] = consumer
}

// RegisterProducer allows you to add (or override) a producer for a media type.
func (o *ProviderServiceAPI) RegisterProducer(mediaType string, producer runtime.Producer) {
	o.customProducers[mediaType] = producer
}

// AddMiddlewareFor adds a http middleware to existing handler
func (o *ProviderServiceAPI) AddMiddlewareFor(method, path string, builder middleware.Builder) {
	um := strings.ToUpper(method)
	if path == "/" {
		path = ""
	}
	o.Init()
	if h, ok := o.handlers[um][path]; ok {
		o.handlers[um][path] = builder(h)
	}
}
