// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Service Provider API
//
//	Schemes:
//	  http
//	Host: provider-service:3335
//	BasePath: /api/v1
//	Version: 1.0.0
//
//	Consumes:
//	  - application/json
//	  - application/x-www-form-urlencoded
//
//	Produces:
//	  - application/json
//
// swagger:meta
package restapi
