// Code generated by go-swagger; DO NOT EDIT.

package public

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/olelarssen/provider/models"
)

// GetYandexCallbackOKCode is the HTTP code returned for type GetYandexCallbackOK
const GetYandexCallbackOKCode int = 200

/*
GetYandexCallbackOK ok response

swagger:response getYandexCallbackOK
*/
type GetYandexCallbackOK struct {

	/*
	  In: Body
	*/
	Payload *models.UserInfo `json:"body,omitempty"`
}

// NewGetYandexCallbackOK creates GetYandexCallbackOK with default headers values
func NewGetYandexCallbackOK() *GetYandexCallbackOK {

	return &GetYandexCallbackOK{}
}

// WithPayload adds the payload to the get yandex callback o k response
func (o *GetYandexCallbackOK) WithPayload(payload *models.UserInfo) *GetYandexCallbackOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get yandex callback o k response
func (o *GetYandexCallbackOK) SetPayload(payload *models.UserInfo) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetYandexCallbackOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetYandexCallbackInternalServerErrorCode is the HTTP code returned for type GetYandexCallbackInternalServerError
const GetYandexCallbackInternalServerErrorCode int = 500

/*
GetYandexCallbackInternalServerError When some error occurs

swagger:response getYandexCallbackInternalServerError
*/
type GetYandexCallbackInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetYandexCallbackInternalServerError creates GetYandexCallbackInternalServerError with default headers values
func NewGetYandexCallbackInternalServerError() *GetYandexCallbackInternalServerError {

	return &GetYandexCallbackInternalServerError{}
}

// WithPayload adds the payload to the get yandex callback internal server error response
func (o *GetYandexCallbackInternalServerError) WithPayload(payload *models.Error) *GetYandexCallbackInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get yandex callback internal server error response
func (o *GetYandexCallbackInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetYandexCallbackInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
