// Code generated by go-swagger; DO NOT EDIT.

package public

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetValidateHandlerFunc turns a function with the right signature into a get validate handler
type GetValidateHandlerFunc func(GetValidateParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetValidateHandlerFunc) Handle(params GetValidateParams) middleware.Responder {
	return fn(params)
}

// GetValidateHandler interface for that can handle valid get validate params
type GetValidateHandler interface {
	Handle(GetValidateParams) middleware.Responder
}

// NewGetValidate creates a new http.Handler for the get validate operation
func NewGetValidate(ctx *middleware.Context, handler GetValidateHandler) *GetValidate {
	return &GetValidate{Context: ctx, Handler: handler}
}

/*
	GetValidate swagger:route GET /validate public getValidate

This API endpoint create, store and returns credentials for new user
*/
type GetValidate struct {
	Context *middleware.Context
	Handler GetValidateHandler
}

func (o *GetValidate) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetValidateParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
