// Code generated by go-swagger; DO NOT EDIT.

package public

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetVkLoginHandlerFunc turns a function with the right signature into a get vk login handler
type GetVkLoginHandlerFunc func(GetVkLoginParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetVkLoginHandlerFunc) Handle(params GetVkLoginParams) middleware.Responder {
	return fn(params)
}

// GetVkLoginHandler interface for that can handle valid get vk login params
type GetVkLoginHandler interface {
	Handle(GetVkLoginParams) middleware.Responder
}

// NewGetVkLogin creates a new http.Handler for the get vk login operation
func NewGetVkLogin(ctx *middleware.Context, handler GetVkLoginHandler) *GetVkLogin {
	return &GetVkLogin{Context: ctx, Handler: handler}
}

/*
	GetVkLogin swagger:route GET /vk/login public getVkLogin

This API endpoint always responds ok
*/
type GetVkLogin struct {
	Context *middleware.Context
	Handler GetVkLoginHandler
}

func (o *GetVkLogin) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetVkLoginParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
