// Code generated by go-swagger; DO NOT EDIT.

package public

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/olelarssen/provider/models"
)

// GetCredentialsOKCode is the HTTP code returned for type GetCredentialsOK
const GetCredentialsOKCode int = 200

/*
GetCredentialsOK get client id and client secret

swagger:response getCredentialsOK
*/
type GetCredentialsOK struct {

	/*
	  In: Body
	*/
	Payload *models.Credentials `json:"body,omitempty"`
}

// NewGetCredentialsOK creates GetCredentialsOK with default headers values
func NewGetCredentialsOK() *GetCredentialsOK {

	return &GetCredentialsOK{}
}

// WithPayload adds the payload to the get credentials o k response
func (o *GetCredentialsOK) WithPayload(payload *models.Credentials) *GetCredentialsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get credentials o k response
func (o *GetCredentialsOK) SetPayload(payload *models.Credentials) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetCredentialsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetCredentialsInternalServerErrorCode is the HTTP code returned for type GetCredentialsInternalServerError
const GetCredentialsInternalServerErrorCode int = 500

/*
GetCredentialsInternalServerError When some error occurs

swagger:response getCredentialsInternalServerError
*/
type GetCredentialsInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetCredentialsInternalServerError creates GetCredentialsInternalServerError with default headers values
func NewGetCredentialsInternalServerError() *GetCredentialsInternalServerError {

	return &GetCredentialsInternalServerError{}
}

// WithPayload adds the payload to the get credentials internal server error response
func (o *GetCredentialsInternalServerError) WithPayload(payload *models.Error) *GetCredentialsInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get credentials internal server error response
func (o *GetCredentialsInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetCredentialsInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
