// Code generated by go-swagger; DO NOT EDIT.

package public

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetYandexLoginHandlerFunc turns a function with the right signature into a get yandex login handler
type GetYandexLoginHandlerFunc func(GetYandexLoginParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetYandexLoginHandlerFunc) Handle(params GetYandexLoginParams) middleware.Responder {
	return fn(params)
}

// GetYandexLoginHandler interface for that can handle valid get yandex login params
type GetYandexLoginHandler interface {
	Handle(GetYandexLoginParams) middleware.Responder
}

// NewGetYandexLogin creates a new http.Handler for the get yandex login operation
func NewGetYandexLogin(ctx *middleware.Context, handler GetYandexLoginHandler) *GetYandexLogin {
	return &GetYandexLogin{Context: ctx, Handler: handler}
}

/*
	GetYandexLogin swagger:route GET /yandex/login public getYandexLogin

This API endpoint always responds ok
*/
type GetYandexLogin struct {
	Context *middleware.Context
	Handler GetYandexLoginHandler
}

func (o *GetYandexLogin) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetYandexLoginParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
