// Code generated by go-swagger; DO NOT EDIT.

package public

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/olelarssen/provider/models"
)

// GetGoogleLoginOKCode is the HTTP code returned for type GetGoogleLoginOK
const GetGoogleLoginOKCode int = 200

/*
GetGoogleLoginOK ok response

swagger:response getGoogleLoginOK
*/
type GetGoogleLoginOK struct {

	/*
	  In: Body
	*/
	Payload *models.Ok `json:"body,omitempty"`
}

// NewGetGoogleLoginOK creates GetGoogleLoginOK with default headers values
func NewGetGoogleLoginOK() *GetGoogleLoginOK {

	return &GetGoogleLoginOK{}
}

// WithPayload adds the payload to the get google login o k response
func (o *GetGoogleLoginOK) WithPayload(payload *models.Ok) *GetGoogleLoginOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get google login o k response
func (o *GetGoogleLoginOK) SetPayload(payload *models.Ok) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetGoogleLoginOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetGoogleLoginInternalServerErrorCode is the HTTP code returned for type GetGoogleLoginInternalServerError
const GetGoogleLoginInternalServerErrorCode int = 500

/*
GetGoogleLoginInternalServerError When some error occurs

swagger:response getGoogleLoginInternalServerError
*/
type GetGoogleLoginInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetGoogleLoginInternalServerError creates GetGoogleLoginInternalServerError with default headers values
func NewGetGoogleLoginInternalServerError() *GetGoogleLoginInternalServerError {

	return &GetGoogleLoginInternalServerError{}
}

// WithPayload adds the payload to the get google login internal server error response
func (o *GetGoogleLoginInternalServerError) WithPayload(payload *models.Error) *GetGoogleLoginInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get google login internal server error response
func (o *GetGoogleLoginInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetGoogleLoginInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
