// Code generated by go-swagger; DO NOT EDIT.

package public

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/olelarssen/provider/models"
)

// GetYandexLoginOKCode is the HTTP code returned for type GetYandexLoginOK
const GetYandexLoginOKCode int = 200

/*
GetYandexLoginOK ok response

swagger:response getYandexLoginOK
*/
type GetYandexLoginOK struct {

	/*
	  In: Body
	*/
	Payload *models.Ok `json:"body,omitempty"`
}

// NewGetYandexLoginOK creates GetYandexLoginOK with default headers values
func NewGetYandexLoginOK() *GetYandexLoginOK {

	return &GetYandexLoginOK{}
}

// WithPayload adds the payload to the get yandex login o k response
func (o *GetYandexLoginOK) WithPayload(payload *models.Ok) *GetYandexLoginOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get yandex login o k response
func (o *GetYandexLoginOK) SetPayload(payload *models.Ok) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetYandexLoginOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetYandexLoginInternalServerErrorCode is the HTTP code returned for type GetYandexLoginInternalServerError
const GetYandexLoginInternalServerErrorCode int = 500

/*
GetYandexLoginInternalServerError When some error occurs

swagger:response getYandexLoginInternalServerError
*/
type GetYandexLoginInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetYandexLoginInternalServerError creates GetYandexLoginInternalServerError with default headers values
func NewGetYandexLoginInternalServerError() *GetYandexLoginInternalServerError {

	return &GetYandexLoginInternalServerError{}
}

// WithPayload adds the payload to the get yandex login internal server error response
func (o *GetYandexLoginInternalServerError) WithPayload(payload *models.Error) *GetYandexLoginInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get yandex login internal server error response
func (o *GetYandexLoginInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetYandexLoginInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
