// Code generated by go-swagger; DO NOT EDIT.

package public

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetGoogleCallbackHandlerFunc turns a function with the right signature into a get google callback handler
type GetGoogleCallbackHandlerFunc func(GetGoogleCallbackParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetGoogleCallbackHandlerFunc) Handle(params GetGoogleCallbackParams) middleware.Responder {
	return fn(params)
}

// GetGoogleCallbackHandler interface for that can handle valid get google callback params
type GetGoogleCallbackHandler interface {
	Handle(GetGoogleCallbackParams) middleware.Responder
}

// NewGetGoogleCallback creates a new http.Handler for the get google callback operation
func NewGetGoogleCallback(ctx *middleware.Context, handler GetGoogleCallbackHandler) *GetGoogleCallback {
	return &GetGoogleCallback{Context: ctx, Handler: handler}
}

/*
	GetGoogleCallback swagger:route GET /google/callback public getGoogleCallback

This API endpoint always responds ok
*/
type GetGoogleCallback struct {
	Context *middleware.Context
	Handler GetGoogleCallbackHandler
}

func (o *GetGoogleCallback) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetGoogleCallbackParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
