// Code generated by go-swagger; DO NOT EDIT.

package public

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetAuthorizeHandlerFunc turns a function with the right signature into a get authorize handler
type GetAuthorizeHandlerFunc func(GetAuthorizeParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetAuthorizeHandlerFunc) Handle(params GetAuthorizeParams) middleware.Responder {
	return fn(params)
}

// GetAuthorizeHandler interface for that can handle valid get authorize params
type GetAuthorizeHandler interface {
	Handle(GetAuthorizeParams) middleware.Responder
}

// NewGetAuthorize creates a new http.Handler for the get authorize operation
func NewGetAuthorize(ctx *middleware.Context, handler GetAuthorizeHandler) *GetAuthorize {
	return &GetAuthorize{Context: ctx, Handler: handler}
}

/*
	GetAuthorize swagger:route GET /authorize public getAuthorize

This API endpoint create, store and returns credentials for new user
*/
type GetAuthorize struct {
	Context *middleware.Context
	Handler GetAuthorizeHandler
}

func (o *GetAuthorize) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetAuthorizeParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
