// Code generated by go-swagger; DO NOT EDIT.

package public

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// NewGetTelegramCallbackParams creates a new GetTelegramCallbackParams object
//
// There are no default values defined in the spec.
func NewGetTelegramCallbackParams() GetTelegramCallbackParams {

	return GetTelegramCallbackParams{}
}

// GetTelegramCallbackParams contains all the bound params for the get telegram callback operation
// typically these are obtained from a http.Request
//
// swagger:parameters GetTelegramCallback
type GetTelegramCallbackParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*tg hash
	  Required: true
	  In: query
	*/
	Hash string
	/*tg payload
	  Required: true
	  In: query
	*/
	Payload string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetTelegramCallbackParams() beforehand.
func (o *GetTelegramCallbackParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	qHash, qhkHash, _ := qs.GetOK("hash")
	if err := o.bindHash(qHash, qhkHash, route.Formats); err != nil {
		res = append(res, err)
	}

	qPayload, qhkPayload, _ := qs.GetOK("payload")
	if err := o.bindPayload(qPayload, qhkPayload, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindHash binds and validates parameter Hash from query.
func (o *GetTelegramCallbackParams) bindHash(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("hash", "query", rawData)
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// AllowEmptyValue: false

	if err := validate.RequiredString("hash", "query", raw); err != nil {
		return err
	}
	o.Hash = raw

	return nil
}

// bindPayload binds and validates parameter Payload from query.
func (o *GetTelegramCallbackParams) bindPayload(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("payload", "query", rawData)
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// AllowEmptyValue: false

	if err := validate.RequiredString("payload", "query", raw); err != nil {
		return err
	}
	o.Payload = raw

	return nil
}
