// Code generated by go-swagger; DO NOT EDIT.

package public

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/olelarssen/provider/models"
)

// GetVkLoginOKCode is the HTTP code returned for type GetVkLoginOK
const GetVkLoginOKCode int = 200

/*
GetVkLoginOK ok response

swagger:response getVkLoginOK
*/
type GetVkLoginOK struct {

	/*
	  In: Body
	*/
	Payload *models.Ok `json:"body,omitempty"`
}

// NewGetVkLoginOK creates GetVkLoginOK with default headers values
func NewGetVkLoginOK() *GetVkLoginOK {

	return &GetVkLoginOK{}
}

// WithPayload adds the payload to the get vk login o k response
func (o *GetVkLoginOK) WithPayload(payload *models.Ok) *GetVkLoginOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get vk login o k response
func (o *GetVkLoginOK) SetPayload(payload *models.Ok) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetVkLoginOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetVkLoginInternalServerErrorCode is the HTTP code returned for type GetVkLoginInternalServerError
const GetVkLoginInternalServerErrorCode int = 500

/*
GetVkLoginInternalServerError When some error occurs

swagger:response getVkLoginInternalServerError
*/
type GetVkLoginInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetVkLoginInternalServerError creates GetVkLoginInternalServerError with default headers values
func NewGetVkLoginInternalServerError() *GetVkLoginInternalServerError {

	return &GetVkLoginInternalServerError{}
}

// WithPayload adds the payload to the get vk login internal server error response
func (o *GetVkLoginInternalServerError) WithPayload(payload *models.Error) *GetVkLoginInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get vk login internal server error response
func (o *GetVkLoginInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetVkLoginInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
