// Code generated by go-swagger; DO NOT EDIT.

package public

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetYandexCallbackHandlerFunc turns a function with the right signature into a get yandex callback handler
type GetYandexCallbackHandlerFunc func(GetYandexCallbackParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetYandexCallbackHandlerFunc) Handle(params GetYandexCallbackParams) middleware.Responder {
	return fn(params)
}

// GetYandexCallbackHandler interface for that can handle valid get yandex callback params
type GetYandexCallbackHandler interface {
	Handle(GetYandexCallbackParams) middleware.Responder
}

// NewGetYandexCallback creates a new http.Handler for the get yandex callback operation
func NewGetYandexCallback(ctx *middleware.Context, handler GetYandexCallbackHandler) *GetYandexCallback {
	return &GetYandexCallback{Context: ctx, Handler: handler}
}

/*
	GetYandexCallback swagger:route GET /yandex/callback public getYandexCallback

This API endpoint always responds ok
*/
type GetYandexCallback struct {
	Context *middleware.Context
	Handler GetYandexCallbackHandler
}

func (o *GetYandexCallback) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetYandexCallbackParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
