// Code generated by go-swagger; DO NOT EDIT.

package public

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/olelarssen/provider/models"
)

// GetAuthorizeReader is a Reader for the GetAuthorize structure.
type GetAuthorizeReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAuthorizeReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAuthorizeOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewGetAuthorizeInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetAuthorizeOK creates a GetAuthorizeOK with default headers values
func NewGetAuthorizeOK() *GetAuthorizeOK {
	return &GetAuthorizeOK{}
}

/* GetAuthorizeOK describes a response with status code 200, with default header values.

authorize
*/
type GetAuthorizeOK struct {
	Payload *models.Authorize
}

func (o *GetAuthorizeOK) Error() string {
	return fmt.Sprintf("[GET /authorize][%d] getAuthorizeOK  %+v", 200, o.Payload)
}
func (o *GetAuthorizeOK) GetPayload() *models.Authorize {
	return o.Payload
}

func (o *GetAuthorizeOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Authorize)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAuthorizeInternalServerError creates a GetAuthorizeInternalServerError with default headers values
func NewGetAuthorizeInternalServerError() *GetAuthorizeInternalServerError {
	return &GetAuthorizeInternalServerError{}
}

/* GetAuthorizeInternalServerError describes a response with status code 500, with default header values.

When some error occurs
*/
type GetAuthorizeInternalServerError struct {
	Payload *models.Error
}

func (o *GetAuthorizeInternalServerError) Error() string {
	return fmt.Sprintf("[GET /authorize][%d] getAuthorizeInternalServerError  %+v", 500, o.Payload)
}
func (o *GetAuthorizeInternalServerError) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetAuthorizeInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
