// Code generated by go-swagger; DO NOT EDIT.

package public

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/olelarssen/provider/models"
)

// GetValidateReader is a Reader for the GetValidate structure.
type GetValidateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetValidateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetValidateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewGetValidateInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetValidateOK creates a GetValidateOK with default headers values
func NewGetValidateOK() *GetValidateOK {
	return &GetValidateOK{}
}

/* GetValidateOK describes a response with status code 200, with default header values.

authorize
*/
type GetValidateOK struct {
	Payload *models.Validate
}

func (o *GetValidateOK) Error() string {
	return fmt.Sprintf("[GET /validate][%d] getValidateOK  %+v", 200, o.Payload)
}
func (o *GetValidateOK) GetPayload() *models.Validate {
	return o.Payload
}

func (o *GetValidateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Validate)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetValidateInternalServerError creates a GetValidateInternalServerError with default headers values
func NewGetValidateInternalServerError() *GetValidateInternalServerError {
	return &GetValidateInternalServerError{}
}

/* GetValidateInternalServerError describes a response with status code 500, with default header values.

When some error occurs
*/
type GetValidateInternalServerError struct {
	Payload *models.Error
}

func (o *GetValidateInternalServerError) Error() string {
	return fmt.Sprintf("[GET /validate][%d] getValidateInternalServerError  %+v", 500, o.Payload)
}
func (o *GetValidateInternalServerError) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetValidateInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
