// Code generated by go-swagger; DO NOT EDIT.

package public

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetValidateParams creates a new GetValidateParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetValidateParams() *GetValidateParams {
	return &GetValidateParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetValidateParamsWithTimeout creates a new GetValidateParams object
// with the ability to set a timeout on a request.
func NewGetValidateParamsWithTimeout(timeout time.Duration) *GetValidateParams {
	return &GetValidateParams{
		timeout: timeout,
	}
}

// NewGetValidateParamsWithContext creates a new GetValidateParams object
// with the ability to set a context for a request.
func NewGetValidateParamsWithContext(ctx context.Context) *GetValidateParams {
	return &GetValidateParams{
		Context: ctx,
	}
}

// NewGetValidateParamsWithHTTPClient creates a new GetValidateParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetValidateParamsWithHTTPClient(client *http.Client) *GetValidateParams {
	return &GetValidateParams{
		HTTPClient: client,
	}
}

/* GetValidateParams contains all the parameters to send to the API endpoint
   for the get validate operation.

   Typically these are written to a http.Request.
*/
type GetValidateParams struct {

	/* AccessToken.

	   access token
	*/
	AccessToken *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get validate params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetValidateParams) WithDefaults() *GetValidateParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get validate params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetValidateParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get validate params
func (o *GetValidateParams) WithTimeout(timeout time.Duration) *GetValidateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get validate params
func (o *GetValidateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get validate params
func (o *GetValidateParams) WithContext(ctx context.Context) *GetValidateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get validate params
func (o *GetValidateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get validate params
func (o *GetValidateParams) WithHTTPClient(client *http.Client) *GetValidateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get validate params
func (o *GetValidateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAccessToken adds the accessToken to the get validate params
func (o *GetValidateParams) WithAccessToken(accessToken *string) *GetValidateParams {
	o.SetAccessToken(accessToken)
	return o
}

// SetAccessToken adds the accessToken to the get validate params
func (o *GetValidateParams) SetAccessToken(accessToken *string) {
	o.AccessToken = accessToken
}

// WriteToRequest writes these params to a swagger request
func (o *GetValidateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.AccessToken != nil {

		// query param access_token
		var qrAccessToken string

		if o.AccessToken != nil {
			qrAccessToken = *o.AccessToken
		}
		qAccessToken := qrAccessToken
		if qAccessToken != "" {

			if err := r.SetQueryParam("access_token", qAccessToken); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
