// Code generated by go-swagger; DO NOT EDIT.

package public

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/olelarssen/provider/models"
)

// PostTokenReader is a Reader for the PostToken structure.
type PostTokenReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostTokenReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostTokenOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewPostTokenInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPostTokenOK creates a PostTokenOK with default headers values
func NewPostTokenOK() *PostTokenOK {
	return &PostTokenOK{}
}

/* PostTokenOK describes a response with status code 200, with default header values.

get client id and client secret
*/
type PostTokenOK struct {
	Payload *models.Token
}

func (o *PostTokenOK) Error() string {
	return fmt.Sprintf("[POST /token][%d] postTokenOK  %+v", 200, o.Payload)
}
func (o *PostTokenOK) GetPayload() *models.Token {
	return o.Payload
}

func (o *PostTokenOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Token)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostTokenInternalServerError creates a PostTokenInternalServerError with default headers values
func NewPostTokenInternalServerError() *PostTokenInternalServerError {
	return &PostTokenInternalServerError{}
}

/* PostTokenInternalServerError describes a response with status code 500, with default header values.

When some error occurs
*/
type PostTokenInternalServerError struct {
	Payload *models.Error
}

func (o *PostTokenInternalServerError) Error() string {
	return fmt.Sprintf("[POST /token][%d] postTokenInternalServerError  %+v", 500, o.Payload)
}
func (o *PostTokenInternalServerError) GetPayload() *models.Error {
	return o.Payload
}

func (o *PostTokenInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
