// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Ok ok
//
// swagger:model ok
type Ok struct {

	// Result of method execution. `ok` in case of success
	// Required: true
	// Enum: [ok]
	Result *string `json:"result"`
}

// Validate validates this ok
func (m *Ok) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateResult(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var okTypeResultPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["ok"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		okTypeResultPropEnum = append(okTypeResultPropEnum, v)
	}
}

const (

	// OkResultOk captures enum value "ok"
	OkResultOk string = "ok"
)

// prop value enum
func (m *Ok) validateResultEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, okTypeResultPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *Ok) validateResult(formats strfmt.Registry) error {

	if err := validate.Required("result", "body", m.Result); err != nil {
		return err
	}

	// value enum
	if err := m.validateResultEnum("result", "body", *m.Result); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this ok based on context it is used
func (m *Ok) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Ok) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Ok) UnmarshalBinary(b []byte) error {
	var res Ok
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
