// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// VkUserInfo vk user info
//
// swagger:model vkUserInfo
type VkUserInfo struct {

	// access token
	AccessToken string `json:"access_token,omitempty"`

	// expires in
	ExpiresIn int64 `json:"expires_in,omitempty"`

	// user id
	UserID int64 `json:"user_id,omitempty"`
}

// Validate validates this vk user info
func (m *VkUserInfo) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this vk user info based on context it is used
func (m *VkUserInfo) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *VkUserInfo) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *VkUserInfo) UnmarshalBinary(b []byte) error {
	var res VkUserInfo
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
